### ISSUE TITLE
Package ‘mRMRe’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by kingcrimsontianyu** [bhklab/mRMRe#30]
Dear developers,
Is this temporary or permanent? Thanks.

**Comment by ChristopherEeles** [comment]
Hi @kingcrimsontianyu,

I believe we were wrongfully removed due to false positives on the automated CRAN build system. A resubmission has already been made and we are waiting on a response from CRAN.

The removal will be temporary, however, it is hard to determine how long resubmission will take. Fingers crossed they aren't too fussed with us.

Sorry for any inconvenience.

Best,
Christopher Eeles
Software Developer

**Comment by kingcrimsontianyu** [comment]
@ChristopherEeles Hey Christopher, thanks for the swift response. Good luck!

**Comment by ChristopherEeles** [comment]
Hi @kingcrimsontianyu,

Just wanted to let you know we were reaccepted to CRAN today, so you can expect to see mRMRe back up shortly.

Best,
Christopher Eeles
Software Developer

**Comment by kingcrimsontianyu** [comment]
@ChristopherEeles Sounds great! Thanks for letting me know.
